### ISSUE TITLE
NoneType' object has no attribute 'getInboxMessagesByReceiver'

### ISSUE THREAD

**Issue by hamiltino** [OpenBazaar/OpenBazaar#1130]
2014-12-17 00:30:27,166 - [1] Market - ERROR - Failed to send message: 'NoneType' object has no attribute 'sendMessage'
2014-12-17 00:30:27,166 - [1] Market - ERROR - Traceback (most recent call last):
  File "/home/tux/Desktop/DesktopStuff/OpenBazaar/node/market.py", line 537, in send_message
    result = self.transport.bitmessage_api.sendMessage(
AttributeError: 'NoneType' object has no attribute 'sendMessage'

2014-12-17 00:30:27,323 - [1] Market - ERROR - Failed to get inbox messages: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'
2014-12-17 00:30:27,323 - [1] Market - ERROR - Traceback (most recent call last):
  File "/home/tux/Desktop/DesktopStuff/OpenBazaar/node/market.py", line 513, in get_messages
    self.transport.bitmessage_api.getInboxMessagesByReceiver(
AttributeError: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'

Debian wheezy

**Comment by johndevor** [comment]
Receiving something similar:

```
2015-03-02 12:49:49,241 - [1] Market - ERROR - Failed to send message: 'NoneType' object has no attribute 'sendMessage'
```

**Comment by johndevor** [comment]
Does Bitmessage need to be installed outside of OpenBazaar?

**Comment by hoffmabc** [comment]
BitMessage is out as of the latest release. Sorry for the trouble. For the record yes BitMessage needed to be installed outside of OpenBazaar.
