### ISSUE TITLE
My router does not have upnp

### ISSUE THREAD

**Issue by Elmit2015** [OpenBazaar/OpenBazaar#1157]
My router does not have a upnp setting. I have setup tcp and udp port forward (12333) from my public static ip to my desktop.

I start with:
 ./openbazaar -j --server-ip 1.3.9.7 --server-port 12333 --disable-stun-check start; tail -f logs/production.log
MarketApplication.start_app(): Disabling upnp setup
Started OpenBazaar Web App at http://127.0.0.1:33791

(process:7744): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

When trying to connect to seed.openlabs.co or Bizarre Co. Seed [EU] I can only watch "Loading merchant..."
BTW, sometimes I get three Connected Markets.

Ubuntu 14.04, ufw disabled

**Comment by hoffmabc** [comment]
Have you tried the connectivity tool tests on the Bizarre Company web site? Does the connectivity work?

I hate to punt but soon we should have a non TCP way of communicating that doesn't require uPnP.

**Comment by Elmit2015** [comment]
Doesn't exactly 
-j --server-ip 1.3.9.7 --server-port 12333 --disable-stun-check
circumvent this?

I can try another port instead of 12333, 

I use now debug warning to see more, but it does not give me a clue:

2015-01-08 09:56:25,398 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: update_settings
2015-01-08 09:56:25,399 - [1] Market - INFO - Letting the network know you are not a notary
2015-01-08 09:56:25,399 - [1] DHT - INFO - Looking for node at: f8eeea6cc4b06dd719a8638d3743ca004f8f89f4
2015-01-08 09:56:25,399 - [1] DHT - INFO - [('seed.openlabs.co', 12345, u'38f2294d84c192e606b234739b5004297ccebf76'), ('eu.seed.bizarre.company', 12345, u'a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb')]
2015-01-08 09:56:37,209 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"get_notaries","params":{}}
2015-01-08 09:56:37,209 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: get_notaries
2015-01-08 09:56:37,209 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 09:56:37,264 - tornado.access - INFO - 200 GET /html/fonts/glyphicons-halflings-regular.woff (127.0.0.1) 0.66ms
2015-01-08 09:56:57,995 - tornado.access - INFO - 200 GET /html/partials/user.html (127.0.0.1) 0.60ms
2015-01-08 09:56:58,039 - tornado.access - INFO - 200 GET /html/img/ajax-loader.gif (127.0.0.1) 0.75ms
2015-01-08 09:56:58,060 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_page","params":{"type":"query_page","findGUID":"38f2294d84c192e606b234739b5004297ccebf76"}}
2015-01-08 09:56:58,061 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_page
2015-01-08 09:56:58,061 - [1] Market - INFO - Searching network for node: 38f2294d84c192e606b234739b5004297ccebf76
2015-01-08 09:56:58,075 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_store_products","params":{"type":"query_store_products","key":"38f2294d84c192e606b234739b5004297ccebf76"}}
2015-01-08 09:56:58,075 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_store_products
2015-01-08 09:56:58,075 - [1] ProtocolHandler - INFO - Searching network for contracts
2015-01-08 09:56:58,089 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"get_notaries","params":{}}
2015-01-08 09:56:58,089 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: get_notaries
2015-01-08 09:56:58,089 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 09:58:11,083 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_messages","params":{"type":"query_messages"}}
2015-01-08 09:58:11,083 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_messages
2015-01-08 09:58:11,083 - [1] ProtocolHandler - INFO - Querying for Messages
2015-01-08 09:58:11,083 - [1] Market - INFO - Listing messages for market: 1
2015-01-08 09:58:11,083 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 09:58:11,102 - [1] Market - ERROR - Failed to get inbox messages: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'
2015-01-08 09:58:11,102 - [1] Market - ERROR - Traceback (most recent call last):
  File "/home/ronald/OpenBazaar/node/market.py", line 513, in get_messages
    self.transport.bitmessage_api.getInboxMessagesByReceiver(
AttributeError: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'

2015-01-08 09:58:11,102 - [1] ProtocolHandler - INFO - Bitmessages: {}
2015-01-08 09:58:11,128 - tornado.access - INFO - 200 GET /html/partials/messages.html (127.0.0.1) 25.69ms
2015-01-08 09:58:11,193 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_messages","params":{"type":"query_messages"}}
2015-01-08 09:58:11,193 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_messages
2015-01-08 09:58:11,193 - [1] ProtocolHandler - INFO - Querying for Messages
2015-01-08 09:58:11,193 - [1] Market - INFO - Listing messages for market: 1
2015-01-08 09:58:11,193 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 09:58:11,212 - [1] Market - ERROR - Failed to get inbox messages: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'
2015-01-08 09:58:11,212 - [1] Market - ERROR - Traceback (most recent call last):
  File "/home/ronald/OpenBazaar/node/market.py", line 513, in get_messages
    self.transport.bitmessage_api.getInboxMessagesByReceiver(
AttributeError: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'

2015-01-08 09:58:11,212 - [1] ProtocolHandler - INFO - Bitmessages: {}
2015-01-08 09:58:41,902 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_page","params":{"type":"query_page","findGUID":"a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb"}}
2015-01-08 09:58:41,902 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_page
2015-01-08 09:58:41,903 - [1] Market - INFO - Searching network for node: a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb
2015-01-08 09:58:41,920 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_store_products","params":{"type":"query_store_products","key":"a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb"}}
2015-01-08 09:58:41,921 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_store_products
2015-01-08 09:58:41,921 - [1] ProtocolHandler - INFO - Searching network for contracts
2015-01-08 09:58:41,942 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"get_notaries","params":{}}
2015-01-08 09:58:41,942 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: get_notaries
2015-01-08 09:58:41,942 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 10:52:54,246 - [1] DHT - INFO - Started Refreshing Routing Table
2015-01-08 11:52:54,246 - [1] DHT - INFO - Started Refreshing Routing Table
2015-01-08 12:02:48,796 - WebSocketHandler - INFO - Websocket closed
2015-01-08 12:02:48,796 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: disconnect_client
2015-01-08 12:03:11,385 - tornado.access - INFO - 200 GET /html/favicon.png (127.0.0.1) 5.19ms
2015-01-08 12:52:54,246 - [1] DHT - INFO - Started Refreshing Routing Table
2015-01-08 13:18:36,328 - tornado.access - INFO - 200 GET /html/index.html (127.0.0.1) 28.11ms
2015-01-08 13:18:36,405 - tornado.access - INFO - 200 GET /html/vendors/angular.min.js (127.0.0.1) 6.45ms
2015-01-08 13:18:36,412 - tornado.access - INFO - 200 GET /html/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js (127.0.0.1) 6.16ms
2015-01-08 13:18:36,413 - tornado.access - INFO - 200 GET /html/vendors/identicon.js (127.0.0.1) 0.79ms
2015-01-08 13:18:36,414 - tornado.access - INFO - 200 GET /html/vendors/pnglib.js (127.0.0.1) 0.70ms
2015-01-08 13:18:36,416 - tornado.access - INFO - 200 GET /html/bower_components/angular-route/angular-route.min.js (127.0.0.1) 0.76ms
2015-01-08 13:18:36,424 - tornado.access - INFO - 200 GET /html/vendors/jquery.min.js (127.0.0.1) 7.75ms
2015-01-08 13:18:36,425 - tornado.access - INFO - 200 GET /html/vendors/bootstrap.min.js (127.0.0.1) 0.76ms
2015-01-08 13:18:36,427 - tornado.access - INFO - 200 GET /html/bower_components/jasny-bootstrap/dist/js/jasny-bootstrap.min.js (127.0.0.1) 1.23ms
2015-01-08 13:18:36,431 - tornado.access - INFO - 200 GET /html/vendors/notifier.js (127.0.0.1) 0.84ms
2015-01-08 13:18:36,432 - tornado.access - INFO - 200 GET /html/services/connection.js (127.0.0.1) 0.71ms
2015-01-08 13:18:36,441 - tornado.access - INFO - 200 GET /html/controllers/contracts.js (127.0.0.1) 8.55ms
2015-01-08 13:18:36,442 - tornado.access - INFO - 200 GET /html/app.js (127.0.0.1) 0.66ms
2015-01-08 13:18:36,443 - tornado.access - INFO - 200 GET /html/controllers/orders.js (127.0.0.1) 0.62ms
2015-01-08 13:18:36,444 - tornado.access - INFO - 200 GET /html/controllers/market.js (127.0.0.1) 0.75ms
2015-01-08 13:18:36,445 - tornado.access - INFO - 200 GET /html/controllers/messages.js (127.0.0.1) 0.43ms
2015-01-08 13:18:36,446 - tornado.access - INFO - 200 GET /html/css/bootstrap.min.css (127.0.0.1) 0.94ms
2015-01-08 13:18:36,447 - tornado.access - INFO - 200 GET /html/controllers/search.js (127.0.0.1) 0.49ms
2015-01-08 13:18:36,448 - tornado.access - INFO - 200 GET /html/controllers/settings.js (127.0.0.1) 0.49ms
2015-01-08 13:18:36,448 - tornado.access - INFO - 200 GET /html/controllers/user.js (127.0.0.1) 0.52ms
2015-01-08 13:18:36,449 - tornado.access - INFO - 200 GET /html/css/animate.css (127.0.0.1) 0.79ms
2015-01-08 13:18:36,450 - tornado.access - INFO - 200 GET /html/css/app.css (127.0.0.1) 0.45ms
2015-01-08 13:18:36,451 - tornado.access - INFO - 200 GET /html/css/messaging.css (127.0.0.1) 0.42ms
2015-01-08 13:18:36,453 - tornado.access - INFO - 200 GET /html/bower_components/jasny-bootstrap/dist/css/jasny-bootstrap.min.css (127.0.0.1) 1.34ms
2015-01-08 13:18:36,454 - tornado.access - INFO - 200 GET /html/css/dark.css (127.0.0.1) 0.49ms
2015-01-08 13:18:36,459 - tornado.access - INFO - 200 GET /html/img/logo_header.png (127.0.0.1) 0.66ms
2015-01-08 13:18:36,685 - tornado.access - INFO - 200 GET /html/partials/user.html (127.0.0.1) 23.61ms
2015-01-08 13:18:36,751 - tornado.access - INFO - 200 GET /html/img/ajax-loader.gif (127.0.0.1) 1.23ms
2015-01-08 13:18:36,800 - WebSocketHandler - INFO - Initialize websockethandler
2015-01-08 13:18:36,800 - WebSocketHandler - INFO - Websocket open
2015-01-08 13:18:36,801 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 13:18:36,821 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"load_page","params":{}}
2015-01-08 13:18:36,822 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: load_page
2015-01-08 13:18:36,822 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"check_order_count","params":{}}
2015-01-08 13:18:36,822 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: check_order_count
2015-01-08 13:18:37,003 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_page","params":{"type":"query_page","findGUID":"a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb"}}
2015-01-08 13:18:37,003 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_page
2015-01-08 13:18:37,004 - [1] Market - INFO - Searching network for node: a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb
2015-01-08 13:18:37,017 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_store_products","params":{"type":"query_store_products","key":"a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb"}}
2015-01-08 13:18:37,017 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_store_products
2015-01-08 13:18:37,018 - [1] ProtocolHandler - INFO - Searching network for contracts
2015-01-08 13:18:37,031 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"get_notaries","params":{}}
2015-01-08 13:18:37,031 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: get_notaries
2015-01-08 13:18:37,031 - [1] Market - INFO - Getting settings info for Market 1

**Comment by Elmit2015** [comment]
Doesn't exactly 
-j --server-ip 1.3.9.7 --server-port 12333 --disable-stun-check
circumvent this?

I can try another port instead of 12333, 

I use now debug warning to see more, but it does not give me a clue:

2015-01-08 09:56:25,398 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: update_settings
2015-01-08 09:56:25,399 - [1] Market - INFO - Letting the network know you are not a notary
2015-01-08 09:56:25,399 - [1] DHT - INFO - Looking for node at: f8eeea6cc4b06dd719a8638d3743ca004f8f89f4
2015-01-08 09:56:25,399 - [1] DHT - INFO - [('seed.openlabs.co', 12345, u'38f2294d84c192e606b234739b5004297ccebf76'), ('eu.seed.bizarre.company', 12345, u'a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb')]
2015-01-08 09:56:37,209 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"get_notaries","params":{}}
2015-01-08 09:56:37,209 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: get_notaries
2015-01-08 09:56:37,209 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 09:56:37,264 - tornado.access - INFO - 200 GET /html/fonts/glyphicons-halflings-regular.woff (127.0.0.1) 0.66ms
2015-01-08 09:56:57,995 - tornado.access - INFO - 200 GET /html/partials/user.html (127.0.0.1) 0.60ms
2015-01-08 09:56:58,039 - tornado.access - INFO - 200 GET /html/img/ajax-loader.gif (127.0.0.1) 0.75ms
2015-01-08 09:56:58,060 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_page","params":{"type":"query_page","findGUID":"38f2294d84c192e606b234739b5004297ccebf76"}}
2015-01-08 09:56:58,061 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_page
2015-01-08 09:56:58,061 - [1] Market - INFO - Searching network for node: 38f2294d84c192e606b234739b5004297ccebf76
2015-01-08 09:56:58,075 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_store_products","params":{"type":"query_store_products","key":"38f2294d84c192e606b234739b5004297ccebf76"}}
2015-01-08 09:56:58,075 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_store_products
2015-01-08 09:56:58,075 - [1] ProtocolHandler - INFO - Searching network for contracts
2015-01-08 09:56:58,089 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"get_notaries","params":{}}
2015-01-08 09:56:58,089 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: get_notaries
2015-01-08 09:56:58,089 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 09:58:11,083 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_messages","params":{"type":"query_messages"}}
2015-01-08 09:58:11,083 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_messages
2015-01-08 09:58:11,083 - [1] ProtocolHandler - INFO - Querying for Messages
2015-01-08 09:58:11,083 - [1] Market - INFO - Listing messages for market: 1
2015-01-08 09:58:11,083 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 09:58:11,102 - [1] Market - ERROR - Failed to get inbox messages: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'
2015-01-08 09:58:11,102 - [1] Market - ERROR - Traceback (most recent call last):
  File "/home/ronald/OpenBazaar/node/market.py", line 513, in get_messages
    self.transport.bitmessage_api.getInboxMessagesByReceiver(
AttributeError: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'

2015-01-08 09:58:11,102 - [1] ProtocolHandler - INFO - Bitmessages: {}
2015-01-08 09:58:11,128 - tornado.access - INFO - 200 GET /html/partials/messages.html (127.0.0.1) 25.69ms
2015-01-08 09:58:11,193 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_messages","params":{"type":"query_messages"}}
2015-01-08 09:58:11,193 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_messages
2015-01-08 09:58:11,193 - [1] ProtocolHandler - INFO - Querying for Messages
2015-01-08 09:58:11,193 - [1] Market - INFO - Listing messages for market: 1
2015-01-08 09:58:11,193 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 09:58:11,212 - [1] Market - ERROR - Failed to get inbox messages: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'
2015-01-08 09:58:11,212 - [1] Market - ERROR - Traceback (most recent call last):
  File "/home/ronald/OpenBazaar/node/market.py", line 513, in get_messages
    self.transport.bitmessage_api.getInboxMessagesByReceiver(
AttributeError: 'NoneType' object has no attribute 'getInboxMessagesByReceiver'

2015-01-08 09:58:11,212 - [1] ProtocolHandler - INFO - Bitmessages: {}
2015-01-08 09:58:41,902 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_page","params":{"type":"query_page","findGUID":"a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb"}}
2015-01-08 09:58:41,902 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_page
2015-01-08 09:58:41,903 - [1] Market - INFO - Searching network for node: a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb
2015-01-08 09:58:41,920 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_store_products","params":{"type":"query_store_products","key":"a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb"}}
2015-01-08 09:58:41,921 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_store_products
2015-01-08 09:58:41,921 - [1] ProtocolHandler - INFO - Searching network for contracts
2015-01-08 09:58:41,942 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"get_notaries","params":{}}
2015-01-08 09:58:41,942 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: get_notaries
2015-01-08 09:58:41,942 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 10:52:54,246 - [1] DHT - INFO - Started Refreshing Routing Table
2015-01-08 11:52:54,246 - [1] DHT - INFO - Started Refreshing Routing Table
2015-01-08 12:02:48,796 - WebSocketHandler - INFO - Websocket closed
2015-01-08 12:02:48,796 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: disconnect_client
2015-01-08 12:03:11,385 - tornado.access - INFO - 200 GET /html/favicon.png (127.0.0.1) 5.19ms
2015-01-08 12:52:54,246 - [1] DHT - INFO - Started Refreshing Routing Table
2015-01-08 13:18:36,328 - tornado.access - INFO - 200 GET /html/index.html (127.0.0.1) 28.11ms
2015-01-08 13:18:36,405 - tornado.access - INFO - 200 GET /html/vendors/angular.min.js (127.0.0.1) 6.45ms
2015-01-08 13:18:36,412 - tornado.access - INFO - 200 GET /html/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js (127.0.0.1) 6.16ms
2015-01-08 13:18:36,413 - tornado.access - INFO - 200 GET /html/vendors/identicon.js (127.0.0.1) 0.79ms
2015-01-08 13:18:36,414 - tornado.access - INFO - 200 GET /html/vendors/pnglib.js (127.0.0.1) 0.70ms
2015-01-08 13:18:36,416 - tornado.access - INFO - 200 GET /html/bower_components/angular-route/angular-route.min.js (127.0.0.1) 0.76ms
2015-01-08 13:18:36,424 - tornado.access - INFO - 200 GET /html/vendors/jquery.min.js (127.0.0.1) 7.75ms
2015-01-08 13:18:36,425 - tornado.access - INFO - 200 GET /html/vendors/bootstrap.min.js (127.0.0.1) 0.76ms
2015-01-08 13:18:36,427 - tornado.access - INFO - 200 GET /html/bower_components/jasny-bootstrap/dist/js/jasny-bootstrap.min.js (127.0.0.1) 1.23ms
2015-01-08 13:18:36,431 - tornado.access - INFO - 200 GET /html/vendors/notifier.js (127.0.0.1) 0.84ms
2015-01-08 13:18:36,432 - tornado.access - INFO - 200 GET /html/services/connection.js (127.0.0.1) 0.71ms
2015-01-08 13:18:36,441 - tornado.access - INFO - 200 GET /html/controllers/contracts.js (127.0.0.1) 8.55ms
2015-01-08 13:18:36,442 - tornado.access - INFO - 200 GET /html/app.js (127.0.0.1) 0.66ms
2015-01-08 13:18:36,443 - tornado.access - INFO - 200 GET /html/controllers/orders.js (127.0.0.1) 0.62ms
2015-01-08 13:18:36,444 - tornado.access - INFO - 200 GET /html/controllers/market.js (127.0.0.1) 0.75ms
2015-01-08 13:18:36,445 - tornado.access - INFO - 200 GET /html/controllers/messages.js (127.0.0.1) 0.43ms
2015-01-08 13:18:36,446 - tornado.access - INFO - 200 GET /html/css/bootstrap.min.css (127.0.0.1) 0.94ms
2015-01-08 13:18:36,447 - tornado.access - INFO - 200 GET /html/controllers/search.js (127.0.0.1) 0.49ms
2015-01-08 13:18:36,448 - tornado.access - INFO - 200 GET /html/controllers/settings.js (127.0.0.1) 0.49ms
2015-01-08 13:18:36,448 - tornado.access - INFO - 200 GET /html/controllers/user.js (127.0.0.1) 0.52ms
2015-01-08 13:18:36,449 - tornado.access - INFO - 200 GET /html/css/animate.css (127.0.0.1) 0.79ms
2015-01-08 13:18:36,450 - tornado.access - INFO - 200 GET /html/css/app.css (127.0.0.1) 0.45ms
2015-01-08 13:18:36,451 - tornado.access - INFO - 200 GET /html/css/messaging.css (127.0.0.1) 0.42ms
2015-01-08 13:18:36,453 - tornado.access - INFO - 200 GET /html/bower_components/jasny-bootstrap/dist/css/jasny-bootstrap.min.css (127.0.0.1) 1.34ms
2015-01-08 13:18:36,454 - tornado.access - INFO - 200 GET /html/css/dark.css (127.0.0.1) 0.49ms
2015-01-08 13:18:36,459 - tornado.access - INFO - 200 GET /html/img/logo_header.png (127.0.0.1) 0.66ms
2015-01-08 13:18:36,685 - tornado.access - INFO - 200 GET /html/partials/user.html (127.0.0.1) 23.61ms
2015-01-08 13:18:36,751 - tornado.access - INFO - 200 GET /html/img/ajax-loader.gif (127.0.0.1) 1.23ms
2015-01-08 13:18:36,800 - WebSocketHandler - INFO - Initialize websockethandler
2015-01-08 13:18:36,800 - WebSocketHandler - INFO - Websocket open
2015-01-08 13:18:36,801 - [1] Market - INFO - Getting settings info for Market 1
2015-01-08 13:18:36,821 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"load_page","params":{}}
2015-01-08 13:18:36,822 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: load_page
2015-01-08 13:18:36,822 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"check_order_count","params":{}}
2015-01-08 13:18:36,822 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: check_order_count
2015-01-08 13:18:37,003 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_page","params":{"type":"query_page","findGUID":"a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb"}}
2015-01-08 13:18:37,003 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_page
2015-01-08 13:18:37,004 - [1] Market - INFO - Searching network for node: a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb
2015-01-08 13:18:37,017 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"query_store_products","params":{"type":"query_store_products","key":"a066e8a369ea87838d8ccf4f7f5dee16d6b5e2cb"}}
2015-01-08 13:18:37,017 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: query_store_products
2015-01-08 13:18:37,018 - [1] ProtocolHandler - INFO - Searching network for contracts
2015-01-08 13:18:37,031 - WebSocketHandler - INFO - [On Message]: {"id":42,"command":"get_notaries","params":{}}
2015-01-08 13:18:37,031 - [1] ProtocolHandler - INFO - (I) ws.ProtocolHandler.handle_request of: get_notaries
2015-01-08 13:18:37,031 - [1] Market - INFO - Getting settings info for Market 1

**Comment by Elmit2015** [comment]
I came a big step further, with the help of http://canyouseeme.org/
It showed that if I set my router to both (TCP/UDP) forwarding, then it does not work, but if I use ONLY TCP it worked.

Now openbazaar starts.

However, when I add a contract with a picture then the picture is not kept. There is also no edit button, only a remove/add. Good news is, that it can also accept Chinese.

I got 14 stores connected and can see at other stores the pictures.

My logfile shows an error (maybe related to the missing picture):

Exception in thread Thread-470:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ronald/OpenBazaar/node/transport.py", line 66, in trigger_callbacks
    cb['cb'](*data)
  File "/home/ronald/OpenBazaar/node/transport.py", line 222, in on_store
    self.dht._on_storeValue(msg)
  File "/home/ronald/OpenBazaar/node/dht.py", line 608, in _on_storeValue
    self.dataStore.setItem(key, value, now, originallyPublished, originalPublisherID, self.market_id)
  File "/home/ronald/OpenBazaar/node/datastore.py", line 109, in setItem
    "market_id": market_id}
  File "/home/ronald/OpenBazaar/node/db_store.py", line 160, in selectEntries
    self._connectToDb()
  File "/home/ronald/OpenBazaar/node/db_store.py", line 21, in _connectToDb
    timeout=10
OperationalError: unable to open database file

Any idea, what that could mean? (permission problem?)

**Comment by reganlawton** [comment]
SQLite is unable to open that file for some reason. It is quite possible you have a permissions issue.

What OS are you using?

**Comment by Elmit2015** [comment]
I use Ubuntu 14.04:

chmod 777 ./db helped, ... thanks ;-)
