### ISSUE TITLE
Contracts

### ISSUE THREAD

**Issue by Elmit2015** [OpenBazaar/OpenBazaar#1158]
1. What does Quantity mean? Is it an inventory and it is counting down the sales or is it the quanitity the buyer has to buy at once? Like a dozen?

2. I attached a picture, but it is not stored. Other contracts do have the picture. What could be wrong?

3. Edit function is missing. Not a good way to re-insert and remove old one. 

4. Clone function is missing, to duplicate similar entries.

5. Forum is not working, I cannot login, since I cannot register, therefore I use this site.

6. What does following log entry mean:
2015-01-09 07:02:53,952 - [1] CryptoPeerConnection - WARNING - There is no public key for encryption
2015-01-09 07:02:55,303 - [1] CryptoPeerConnection - WARNING - There is no public key for encryption
2015-01-09 07:02:55,525 - [1] CryptoPeerConnection - WARNING - There is no public key for encryption
Exception in thread Thread-2764:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ronald/OpenBazaar/node/transport.py", line 66, in trigger_callbacks
    cb['cb'](*data)
  File "/home/ronald/OpenBazaar/node/transport.py", line 236, in on_findNodeResponse
    self.dht.on_findNodeResponse(self, msg)
  File "/home/ronald/OpenBazaar/node/dht.py", line 334, in on_findNodeResponse
    search.callback(search.shortlist)
  File "/home/ronald/OpenBazaar/node/dht.py", line 507, in <lambda>
    self.storeKeyValue(msg, findKey, value, originalPublisherID, age)
  File "/home/ronald/OpenBazaar/node/dht.py", line 577, in storeKeyValue
    key, value, now, originallyPublished, originalPublisherID, market_id=self.market_id
  File "/home/ronald/OpenBazaar/node/datastore.py", line 136, in setItem
    'market_id': market_id
  File "/home/ronald/OpenBazaar/node/db_store.py", line 115, in updateEntries
    cur.execute(query, tuple(sets + wheres))
OperationalError: database is locked

2015-01-09 07:02:56,918 - [1] CryptoPeerConnection - WARNING - There is no public key for encryption
2015-01-09 07:02:57,145 - [1] CryptoPeerConnection - WARNING - There is no public key for encryption
2015-01-09 07:02:57,284 - [1] CryptoPeerConnection - WARNING - There is no public key for encryption

**Comment by Elmit2015** [comment]
I tried another picture and it worked. Is there a size limit? or type limit?

**Comment by theblacksquid** [comment]
@Elmit2015 : We don't use the forum anymore, we encourage people to use the <a href="http://www.reddit.com/r/OpenBazaar">subreddit</a> instead.

And about the definition of quantity (or any of the line items on the contract, for that matter) is still up for discussion, since the definition of what is and is not on the contract is still being finalized. @drwasho might be able to answer some of your questions specific to the contract. @hoffmabc might be able to help with the issues with the webclient.

**Comment by hoffmabc** [comment]
@Elmit2015 can you please break these issues up into atomic issues so that we can take action against them? Sorry but it's very complex and makes it hard to track in GitHub issues.
