### ISSUE TITLE
Issue running on OS X

### ISSUE THREAD

**Issue by fanquake** [OpenBazaar/OpenBazaar#1228]
Running the latest code in the develop branch.

```
OpenBazaar configuration finished!
Run './openbazaar --disable-sqlite-crypt start; tail -F logs/production.log' to start OpenBazaar and output logs.



xxx:openbazaar xxx$ ./openbazaar --disable-sqlite-crypt start; tail -F 
logs/production.log
Checking NAT Status...
{'nat_type': 'Full Cone', 'external_ip': '106.68.174.90', 'external_port': 57184}
Process Process::openbazaar_daemon::target(start_node):
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "node/openbazaar_daemon.py", line 392, in start_node
    application = MarketApplication(ob_ctx)
  File "node/openbazaar_daemon.py", line 211, in __init__
    self.transport.join_network(peers)
  File "node/transport.py", line 844, in join_network
    db_peers = self.get_past_peers()
  File "node/transport.py", line 868, in get_past_peers
    return [(peer['hostname'], peer['port']) for peer in result]
KeyError: 'hostname'
    return self.callback()
  File "node/dht.py", line 40, in synced_f
    return f(self, *args, **kwargs)
  File "node/dht.py", line 331, in _refresh_node
    self._republish_data()
  File "node/dht.py", line 40, in synced_f
    return f(self, *args, **kwargs)
  File "node/dht.py", line 354, in _republish_data
    self._threadedRepublishData()
AttributeError: 'DHT' object has no attribute '_threadedRepublishData'
```

**Comment by hoffmabc** [comment]
You can't be using the latest develop because that method no longer exists.

**Comment by hoffmabc** [comment]
Maybe do 
'''
git status
'''

And verify

**Comment by fanquake** [comment]
@hoffmabc Just what I was about to post. 

```
xxx:openbazaar xxx$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean
xxx:openbazaar xxx$ git log
commit 0c7ba0aaf551c65cb9d2a5faa66e6e61e0a4bbe8
Author: Brian Hoffman <brianchoffman@gmail.com>
Date:   Sat Apr 18 09:38:17 2015 -0400

    Fix notary add/remove

commit d18c4f4c7d5bf5dcfcb1aa1f808548147368bb93
Author: Brian Hoffman <brianchoffman@gmail.com>
Date:   Sat Apr 18 09:09:02 2015 -0400

    Warning for Adding Store Node

commit 6bb03c203165d35a52abb48eb3ff57f0df947942
```

**Comment by fanquake** [comment]
Running git clean solved this.
