### ISSUE TITLE
Error on shutdown

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#1247]
When running ````./openbazaar stop```` I get the following error consistently:

````
openbazaar::start_io_loop Exception: 'MarketApplication' object has no attribute 'loop'
Process Process::openbazaar_daemon::target(start_node):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "node/openbazaar_daemon.py", line 397, in start_node
    start_io_loop()
  File "node/openbazaar_daemon.py", line 329, in start_io_loop
    tornado.ioloop.IOLoop.instance().start()
  File "/home/node/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 812, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "node/openbazaar_daemon.py", line 317, in shutdown
    self.loop.stop()
AttributeError: 'MarketApplication' object has no attribute 'loop'
````

I assume this is related to changes in #1240, @gubatron you might want to check this out.

**Comment by gubatron** [comment]
thanks, will fix.

**Comment by gubatron** [comment]
still see the error? can this be closed @SamPatt

**Comment by SamPatt** [comment]
Haven't seen it @gubatron, thanks.
