### ISSUE TITLE
OpenBazaar went into continuous exception loop

### ISSUE THREAD

**Issue by arnuschky** [OpenBazaar/OpenBazaar#1265]
Happened when I clicked on seed merchant

```
2015-05-01 14:56:18,374 - tornado.access - WARNING - 404 GET /html/%7B%7Bmyself.settings.avatar_url%7D%7D (127.0.0.1) 0.75ms
2015-05-01 14:56:18,375 - tornado.access - WARNING - 404 GET /html/%7B%7Bpeer.avatar_url%7D%7D (127.0.0.1) 0.66ms
2015-05-01 14:56:18,376 - tornado.access - WARNING - 404 GET /html/%7B%7Bshout.avatar_url%7D%7D (127.0.0.1) 0.61ms
2015-05-01 14:56:18,694 - tornado.application - ERROR - Uncaught exception in /ws
Traceback (most recent call last):
  File "/home/arne/crypto.git/OpenBazaar.git/env/local/lib/python2.7/site-packages/tornado/websocket.py", line 369, in _run_callback
    callback(*args, **kwargs)
  File "node/ws.py", line 1468, in on_message
    if self.app_handler.handle_request(self, request):
  File "node/ws.py", line 1362, in handle_request
    self._handlers[command](socket_handler, params)
  File "node/ws.py", line 464, in client_query_page
    lambda msg, query_id=query_id: cb(msg, query_id)
  File "node/market.py", line 788, in query_page
    self.transport.send(msg, find_guid, callback)
  File "node/transport.py", line 918, in send
    peer = self.dht.routing_table.get_contact(send_to)
  File "node/routingtable.py", line 406, in get_contact
    bucket_index = self.kbucket_index(node_id)
  File "node/routingtable.py", line 507, in kbucket_index
    if bucket.key_in_range(key)
  File "node/kbucket.py", line 171, in key_in_range
    key = int(key, base=16)
ValueError: invalid literal for int() with base 16: 'seed1'
```

Using 16efdf4

**Comment by arnuschky** [comment]
Reproducible when doing `stop`, `start` and then clicking on `seed0`

**Comment by hoffmabc** [comment]
This is a known issue and dupe, but thank you for reporting. It should be fixed in the next build.
