### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by RyuzakiKK** [OpenBazaar/OpenBazaar#1297]
I'm using Arch Linux x64 with the last git version of openbazaar.

After openbazaar start I got this error:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/var/lib/openbazaar/node/openbazaar.py", line 460, in <module>
        main()
      File "/var/lib/openbazaar/node/openbazaar.py", line 452, in main
        start(arguments)
      File "/var/lib/openbazaar/node/openbazaar.py", line 389, in start
        ensure_database_setup(ob_ctx, defaults)
      File "/var/lib/openbazaar/node/openbazaar.py", line 351, in ensure_database_setup
        setup_db.setup_db(db_path, ob_ctx.disable_sqlite_crypt)
      File "node/setup_db.py", line 230, in setup_db
        with dbapi2.connect(db_path) as con:
    sqlite3.OperationalError: unable to open database file

**Comment by gubatron** [comment]
did you run `./configure.sh` before, looks like your database hasn't been setup yet.

**Comment by RyuzakiKK** [comment]
I used this https://aur.archlinux.org/packages/openbazaar-git/ so I thought that I didn't need to run configure.sh.
Anyway now I did it but I still receive this error.

A side note, in the line 41 of configure.sh for arch virtualenv need to be virtualenv2.

**Comment by hoffmabc** [comment]
Ok I will have to get a build of ArchLinux because I don't have one to test on.
