### ISSUE TITLE
Endless refresh on `Orders -> My Purchases` page

### ISSUE THREAD

**Issue by moldcraft** [OpenBazaar/OpenBazaar#1355]
After I submitted a order (my first order), I went to `Orders -> My Purchases` and I get [this](https://vid.me/pjNs)

##### Console log

```
Started websocket: ws://127.0.0.1:56442/ws
connection.js:64 WebSocket {}
market.js:650 settings Object {email: "", PGPPubKey: "", bitmessage: "", pubkey: "", secret: ""…}
connection.js:21 0
connection.js:55 On Message [ myself ]:  Object {id: 812053, result: Object}
orders.js:45 /orders/purchases
connection.js:21 1
market.js:650 settings Object {countryCode: "XX", homepage: "", stateRegion: "Xxxxx", guid: "xxxxxxxxxxx", id: 1…}
connection.js:43 closed CloseEvent {}
connection.js:44 The websocket closed unexpectedly. Refreshing.
```

**Comment by moldcraft** [comment]
Also I can't chat. I write something, press Enter and the page refreshes and nothing appears in chat.

#### Console log

```
```

**Comment by hoffmabc** [comment]
What do you get in your /logs/production.log file?

**Comment by moldcraft** [comment]
Today (after I started OpenBazaar) the refresh problem with refresh is gone. I can write in chat and open `Orders -> My Purchases` page.

Here is the log from yesterday: http://sourcebox.io/a3a0d5bda89db1602679998855d7bbb2 (I copied it before I started OpenBazaar)

**Comment by moldcraft** [comment]
Today I started OpenBazaar, and right after the browser tab was opened, I tried to open `Orders -> My Purchases` and again, the endless refresh.

`logs/production.log` contains this:

```
2015-07-08 00:58:01,450 - [1] CryptoPeerConnection - WARNING - There is no public key for encryption
2015-07-08 00:59:43,078 - [1] OptimizedTreeRoutingTable - ERROR - Attempted to remove absent contact 63c771b6b5c8acf0fcef7fa749a129000ab7daef.
2015-07-08 12:27:32,449 - tornado.application - ERROR - Uncaught exception in /ws
Traceback (most recent call last):
  File "/home/i/Soft/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/websocket.py", line 369, in _run_callback
    callback(*args, **kwargs)
  File "node/ws.py", line 1474, in on_message
    if self.app_handler.handle_request(self, request):
  File "node/ws.py", line 1368, in handle_request
    self._handlers[command](socket_handler, params)
  File "node/ws.py", line 484, in client_query_orders
    orders = self.market.orders.get_orders(page, merchant=False)
  File "node/orders.py", line 410, in get_orders
    order = self.get_order(result['order_id'])
  File "node/orders.py", line 230, in get_order
    buyer_data_json = self.get_buyer_json(_order['signed_contract_body'], _order['state'])
  File "node/orders.py", line 163, in get_buyer_json
    print raw_contract, state
IOError: [Errno 5] Input/output error
2015-07-08 12:27:32,728 - tornado.application - ERROR - Uncaught exception in /ws
```

**Comment by moldcraft** [comment]
Yesterday I wasn't able to access MyPurchases page even after restart.

Today I started OpenBazaar and again I can't access MyPurchases page (same above error)

**Comment by moldcraft** [comment]
Again a refresh problem:

* Open `Messages -> Sent`
* (There I have a ~1 week old message) I click on `Reply` and the page refreshes and I am redirected to HomePage

`logs/production.log`

```

2015-07-13 13:35:53,842 - tornado.application - ERROR - Uncaught exception in /ws
Traceback (most recent call last):
  File "/home/i/Soft/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/websocket.py", line 369, in _run_callback
    callback(*args, **kwargs)
  File "node/ws.py", line 1474, in on_message
    if self.app_handler.handle_request(self, request):
  File "node/ws.py", line 1368, in handle_request
    self._handlers[command](socket_handler, params)
  File "node/ws.py", line 484, in client_query_orders
    orders = self.market.orders.get_orders(page, merchant=False)
  File "node/orders.py", line 410, in get_orders
    order = self.get_order(result['order_id'])
  File "node/orders.py", line 230, in get_order
    buyer_data_json = self.get_buyer_json(_order['signed_contract_body'], _order['state'])
  File "node/orders.py", line 163, in get_buyer_json
    print raw_contract, state
IOError: [Errno 5] Input/output error
2015-07-13 13:36:35,404 - CryptoPeerListener - ERROR - Cannot unpack data: unpack requires a string argument of length 2
```

P.S. I still can't access MyPurchases page.
