### ISSUE TITLE
Can't create new transactions

### ISSUE THREAD

**Issue by rllola** [OpenBazaar/OpenBazaar#1373]
I am using ubuntu 14.04, I have been cloning the branch `develop` (latest commit #c77f9ae0019e9d1c412574465529873c35451a5a) to run a store. 
When trying to create a new contract, I encounter this error : 
```
2015-08-08 15:01:57,916 - [1] Market - DEBUG - Generating new pubkey for contract
2015-08-08 15:01:57,916 - DB - DEBUG - query: SELECT * FROM keystore WHERE "1" = ? ORDER BY id ASC 
2015-08-08 15:01:57,917 - tornado.application - ERROR - Uncaught exception in /ws
Traceback (most recent call last):
  File "/home/lola/Workspace/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/websocket.py", line 369, in _run_callback
    callback(*args, **kwargs)
  File "node/ws.py", line 1455, in on_message
    if self.app_handler.handle_request(self, request):
  File "node/ws.py", line 1349, in handle_request
    self._handlers[command](socket_handler, params)
  File "node/ws.py", line 566, in client_create_contract
    self.market.save_contract(contract)
  File "node/market.py", line 257, in save_contract
    seller['seller_BTC_uncompressed_pubkey'] = self.generate_new_pubkey(contract_id)
  File "node/market.py", line 224, in generate_new_pubkey
    next_key_id = int(self.db_connection.select_entries("keystore", select_fields="id")) + 1
TypeError: int() argument must be a string or a number, not 'list'
```
In order to solve this problem I have changed locally the `int()` function to `len()` and it fixed the problem.

**Comment by saltduck** [comment]
I think it is better that changes select_fields="id" to select_fields="max(id)"

**Comment by richwestcoast** [comment]
I am also experiencing this issue. 

Changed from int() to len() fixes this on line 224 on *node/market.py*

**Comment by SamPatt** [comment]
@richwestcoast This code is completely outdated and not supported. Please use the new repositories for OpenBazaar:

https://blog.openbazaar.org/three-openbazaar-code-repositories-created/

**Comment by richwestcoast** [comment]
Okay apologies. Only just started looking into OpenBazaar. Thanks for the link :D
