### ISSUE TITLE
Install failure on OSX

### ISSUE THREAD

**Issue by yalcrab26** [OpenBazaar/OpenBazaar#314]
After ./run.sh I get the following
```bash
Production Mode
File ob.db does not exist. Running setup script.
Traceback (most recent call last):
  File "node/setup_db.py", line 11, in <module>
    from pysqlcipher import dbapi2 as sqlite
ImportError: No module named pysqlcipher
somebody's macbook pro:OpenBazaar yalcrab26$ Traceback (most recent call last):
  File "node/tornadoloop.py", line 3, in <module>
    import tornado.web
ImportError: No module named tornado.web
```

**Comment by Renelvon** [comment]
@dionyziz If you believe our latest update to `pysqlcipher 2.6.4` fixes these problems, feel free to close the issue.

**Comment by hoffmabc** [comment]
No longer use pysqlcipher.
