### ISSUE TITLE
Installation failed on ubuntu

### ISSUE THREAD

**Issue by ezaron** [OpenBazaar/OpenBazaar#611]
```bash
machine:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```

The `./configure.sh` script dies with this message:

```bash
Setting up python-virtualenv (1.11.4-1) ...
+ '[' '!' -d ./env ']'
+ virtualenv env
New python executable in env/bin/python
Installing setuptools, pip...done.
+ ./env/bin/pip install ./pysqlcipher
Traceback (most recent call last):
  File "./env/bin/pip", line 7, in <module>
    from pip import main
  File "/home/ezaron/opt/src/OpenBazaar/env/local/lib/python2.7/site-packages/pip/__init__.py", line 9, in <module>
    from pip.log import logger
  File "/home/ezaron/opt/src/OpenBazaar/env/local/lib/python2.7/site-packages/pip/log.py", line 9, in <module>
    from pip._vendor import colorama, pkg_resources
  File "/home/ezaron/opt/src/OpenBazaar/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2717, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/home/ezaron/opt/src/OpenBazaar/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 682, in subscribe
    callback(dist)
  File "/home/ezaron/opt/src/OpenBazaar/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2717, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/home/ezaron/opt/src/OpenBazaar/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2255, in activate
    list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))
  File "/home/ezaron/opt/src/OpenBazaar/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 1851, in declare_namespace
    path = sys.modules[parent].__path__
KeyError: 'pydap'
```

**Comment by Renelvon** [comment]
Closing issue as abandoned.
