### ISSUE TITLE
pybitcointools null exception

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar#645]
This may need to be reported upstream, but I'm seeing this today.

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/brianhoffman/Projects/merge/083014/OpenBazaar/node/trust.py", line 103, in get_history
    history = pybitcointools.history(addr)
  File "/Library/Python/2.7/site-packages/pybitcointools/bci.py", line 28, in history
    data = make_request('http://blockchain.info/address/%s?format=json&offset=%s' % (addr,offset))
  File "/Library/Python/2.7/site-packages/pybitcointools/bci.py", line 13, in make_request
    raise Exception(p)
Exception: null
```

**Comment by hoffmabc** [comment]
No longer see this issue.
