### ISSUE TITLE
ValueError: invalid literal for long() with base 16:

### ISSUE THREAD

**Issue by Rav3nPL** [OpenBazaar/OpenBazaar#738]
When I press "republish" log shows me:
```
2014-10-04 21:28:09,578 - tornado.application - ERROR - Uncaught exception in /ws
Traceback (most recent call last):
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/websocket.py", line 369, in _run_callback
    callback(*args, **kwargs)
  File "/home/open/OpenBazaar/node/ws.py", line 1151, in on_message
    if self.app_handler.handle_request(self, request):
  File "/home/open/OpenBazaar/node/ws.py", line 1063, in handle_request
    self._handlers[command](socket_handler, params)
  File "/home/open/OpenBazaar/node/ws.py", line 373, in client_republish_contracts
    self.market.republish_contracts()
  File "/home/open/OpenBazaar/node/market.py", line 353, in republish_contracts
    self.transport.guid
  File "/home/open/OpenBazaar/node/transport.py", line 157, in store
    self.dht.iterativeStore(*args, **kwargs)
  File "/home/open/OpenBazaar/node/dht.py", line 532, in iterativeStore
    originalPublisherID=originalPublisherID, age=age: self.storeKeyValue(msg,
  File "/home/open/OpenBazaar/node/dht.py", line 701, in iterativeFindNode
    self._iterativeFind(key, [], callback=callback)
  File "/home/open/OpenBazaar/node/dht.py", line 733, in _iterativeFind
    closeNodes = self.routingTable.findCloseNodes(key, constants.alpha, self.settings['guid'])
  File "/home/open/OpenBazaar/node/routingtable.py", line 238, in findCloseNodes
    bucketIndex = self.kbucketIndex(key)
  File "/home/open/OpenBazaar/node/routingtable.py", line 356, in kbucketIndex
    valKey = long(key, 16)
ValueError: invalid literal for long() with base 16: '-----BEGIN PGP SIGNED MESSAGE----- Hash: SHA1  { "Seller": { "seller_GUID": "cf25279ceef595bc31bbc7 8667c43a9ce087519b",  "seller_BTC_uncompressed_pubke y": "0478adfce0b12a801c7a155580baaf744df4ccb33d'
```

**Comment by Renelvon** [comment]
Closing as presumably fixed.
