### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by Rav3nPL** [OpenBazaar/OpenBazaar#814]
Trying to found, what is causing "cascade" of spam that fill log.
Maybe this help:
```
2014-10-16 19:08:11,076 - [1] KBucket - DEBUG - [getContact] 72492f065128d334db9b9dcc57ebae238f7c155b
2014-10-16 19:08:11,080 - [1] KBucket - DEBUG - [getContact] Found { guid: 72492f065128d334db9b9dcc57ebae238f7c155b, ip: 199.120.90.18, port: 12345, pubkey: 04f08edaeaaa3b4821e13c15e4cd71aa3e35de629068feacfc08080da70532b7ab2c6
d6c3201cdb599ab13fe1158b8e8a92b2d94a48bb22c9ded441b9194976839 }
2014-10-16 19:08:11,081 - [1] DHT - DEBUG - Adding new peer to active peers list: [u'ebc311eb3b69a7f62cc5d32231fdda2fe62a8449', u'tcp://66.176.114.156:12345', u'04a0288ac463b4ef3baedf2f29127b1ddd9df79b7cca1d7859df2ae61e020cbcb
bfc1eb70000197b77df93d40e2f189543fa846ddcc4647052b164a5dcd42c0657', u'Default']
2014-10-16 19:08:11,080 - [1] CryptoPeerConnection - DEBUG - ['{"senderNick": "Digital Goods", "pubkey": "04f44b37c4c71e9f7f7725e739c007e1dee1827f36b12a46c39876efe4e7a68cdb3c43a5d922c47258da09758abb187609907e4c2c770533903a10f5
7340f2340a", "senderGUID": "e286c083b4a10ea6fdc2851051eb3f2335b62677", "type": "ok"}']
2014-10-16 19:08:11,082 - tornado.general - DEBUG - Error deleting fd from IOLoop
Traceback (most recent call last):
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 688, in remove_handler
    self._impl.unregister(fd)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 75, in unregister
    self._map[socket] -= 1
KeyError: <zmq.sugar.socket.Socket object at 0x7f771c6cfd50>
2014-10-16 19:08:11,081 - [1] KBucket - DEBUG - [getContact] ebc311eb3b69a7f62cc5d32231fdda2fe62a8449
2014-10-16 19:08:11,079 - [1] KBucket - DEBUG - [getContact] Found { guid: 87b99cce6eb9de7077fcb004da76ddda37c1d1bd, ip: 76.186.28.29, port: 12345, pubkey: 0448f27ac6835f58b8ad0ef68f2ea7a092d6cd5f0c783b0a59ce4299b442a8ba7fbaf2
1d221e65f193198cea4939d27becbac0fc438b915f2fcbe3b6a162221f40 }
2014-10-16 19:08:11,078 - [1] KBucket - DEBUG - [getContact] 44b4cde565804a79bb86b4914bbd74793afe5b95
2014-10-16 19:08:11,099 - [1] KBucket - DEBUG - [getContact] Found { guid: 44b4cde565804a79bb86b4914bbd74793afe5b95, ip: 178.62.254.50, port: 12345, pubkey: 04304f8028cb06daa2198a40924f13d55681edc5b5ecae3c7fad607fbed7e16c69116
12d590ff6a8f452f6c7ef9c0cf64d080f2683aba80e3b23c8f5f044621b69 }
2014-10-16 19:08:11,097 - tornado.general - ERROR - Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 442, in _handle_events
    self._rebuild_io_state()
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 505, in _rebuild_io_state
    self._update_handler(state)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 523, in _update_handler
    self.io_loop.update_handler(self.socket, state)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 681, in update_handler
    self._impl.modify(fd, events | self.ERROR)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 112, in modify
    return self._poller.modify(fd, self._map_events(events))
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 61, in modify
    self.register(socket, flags)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 47, in register
    self.sockets[idx] = (socket, flags)
IndexError: list assignment index out of range
2014-10-16 19:08:11,105 - tornado.general - DEBUG - Error deleting fd from IOLoop
Traceback (most recent call last):
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 688, in remove_handler
    self._impl.unregister(fd)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 72, in unregister
    self.sockets.pop(idx)
IndexError: pop index out of range
2014-10-16 19:08:11,105 - tornado.application - ERROR - Exception in callback None
Traceback (most recent call last):
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 837, in start
    handler_func(fd_obj, events)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 442, in _handle_events
    self._rebuild_io_state()
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 505, in _rebuild_io_state
    self._update_handler(state)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 523, in _update_handler
    self.io_loop.update_handler(self.socket, state)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 681, in update_handler
    self._impl.modify(fd, events | self.ERROR)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 112, in modify
    return self._poller.modify(fd, self._map_events(events))
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 61, in modify
    self.register(socket, flags)
  File "/home/open/OpenBazaar/env/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 47, in register
    self.sockets[idx] = (socket, flags)
IndexError: list assignment index out of range
2014-10-16 19:08:11,098 - [1] DHT - DEBUG - Adding new peer to active peers list: [u'7eed3821bc399c8859762464dac22d9a3090f3cd', u'tcp://76.186.28.29:12344', u'0467e24c9a63ec45742cca60899bef4cb7d03f77a9c8170c72ec31097c75470afb9
944b34a097dca4b1cb5371381401cf1a6267d69387c9a542ac4fa00356e036b', u'EpicTees']
2014-10-16 19:08:11,118 - [1] DHT - DEBUG - This peer is already known and up to date
2014-10-16 19:08:11,118 - [1] DHT - DEBUG - Adding new peer to active peers list: [u'af7f875b2929c10aa9110f4faae5d83299a07a56', u'tcp://50.138.190.92:12345', u'046a60d58513e95d265b184777d0e569b4e9c0296a0eeaeecdc3dca4c8a358f49f
f5c567870fa9f58e8541fd24b535dcc630a2fbcea151d697e4dbc1d5456ba3d7', u'House of Argiope']
2014-10-16 19:08:11,118 - [1] KBucket - DEBUG - [getContact] af7f875b2929c10aa9110f4faae5d83299a07a56
2014-10-16 19:08:11,119 - [1] KBucket - DEBUG - [getContact] Found { guid: af7f875b2929c10aa9110f4faae5d83299a07a56, ip: 50.138.190.92, port: 12345, pubkey: 046a60d58513e95d265b184777d0e569b4e9c0296a0eeaeecdc3dca4c8a358f49ff5c
567870fa9f58e8541fd24b535dcc630a2fbcea151d697e4dbc1d5456ba3d7 }
```
Latest dev

**Comment by hoffmabc** [comment]
Not using zmq anymore so closing.
