### ISSUE TITLE
OSError: [Errno 13] Permission denied: 'env'

### ISSUE THREAD

**Issue by Squ34k3rZ** [OpenBazaar/OpenBazaar#969]
```
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 984, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1158, in install_python
    mkdir(lib_dir)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 447, in mkdir
    os.makedirs(path)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: 'env'
```
Getting this error

**Comment by hoffmabc** [comment]
Thanks for helping resolve this @benemorius. I believe this is no longer an issue @theblacksquid so closing.
