### ISSUE TITLE
Errors While Attempting to Change Settings

### ISSUE THREAD

**Issue by Eylrid** [OpenBazaar/OpenBazaar#995]
I downloaded and ran the new Windows version on Windows Vista. I was changing the settings when a "openbazaar.exe stopped working" message came up. The terminal had these errors:

Exception in thread Thread-151:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "threading.pyo", line 763, in run
  File "node\connection.pyo", line 146, in start_handshake
  File "node\connection.pyo", line 62, in send_raw
  File "zmq\eventloop\zmqstream.pyo", line 246, in send
  File "zmq\eventloop\zmqstream.pyo", line 260, in send_multipart
  File "zmq\eventloop\zmqstream.pyo", line 511, in _add_io_state
  File "zmq\eventloop\zmqstream.pyo", line 523, in _update_handler
  File "tornado\ioloop.pyo", line 681, in update_handler
  File "zmq\eventloop\ioloop.pyo", line 112, in modify
  File "zmq\sugar\poll.pyo", line 61, in modify
  File "zmq\sugar\poll.pyo", line 47, in register
IndexError: list assignment index out of range

Exception in thread Thread-256:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "threading.pyo", line 763, in run
  File "node\transport.pyo", line 66, in trigger_callbacks
  File "node\transport.pyo", line 222, in on_store
  File "node\dht.pyo", line 608, in _on_storeValue
  File "node\datastore.pyo", line 109, in setItem
  File "node\db_store.pyo", line 187, in selectEntries
ProgrammingError: SQLite objects created in a thread can only be used in that sa
me thread.The object was created in thread id 840 and this is thread id 5244

Exception in thread Thread-252:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "threading.pyo", line 763, in run
  File "node\transport.pyo", line 66, in trigger_callbacks
  File "node\transport.pyo", line 236, in on_findNodeResponse
  File "node\dht.pyo", line 334, in on_findNodeResponse
  File "node\dht.pyo", line 507, in <lambda>
  File "node\dht.pyo", line 577, in storeKeyValue
  File "node\datastore.pyo", line 109, in setItem
  File "node\db_store.pyo", line 187, in selectEntries
ProgrammingError: SQLite objects created in a thread can only be used in that sa
me thread.The object was created in thread id 4052 and this is thread id 840

Assertion failed: Connection reset by peer (bundled\zeromq\src\tcp.cpp:48)

**Comment by hoffmabc** [comment]
Should be fixed. No zeromq anymore either.
